# Generated by Django 4.0.1 on 2022-01-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tabletype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, max_length=5, null=True)),
                ('categoryMenuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorymenu')),
                ('subCategoryMenuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategorymenu')),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
