# Generated by Django 4.0.1 on 2022-01-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymenu',
            name='categoryMenuId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.categorymenu'),
        ),
    ]
