# Generated by Django 4.0.1 on 2022-01-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subcategorymenu_categorymenuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeForOrder',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorymenu',
            name='categoryMenuId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorymenu'),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timefororder'),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('date', 'time', 'orderId')},
        ),
    ]
